import io
import csv
import json
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch

from app.schemas.reporting import ReportDataPayload


class ReportExportService:
    @staticmethod
    def export_pdf(payload: ReportDataPayload) -> bytes:
        """
        Generate a publication-grade PDF intelligence report using ReportLab.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#0f172a'),
            spaceAfter=4
        )
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#ea580c'),  # Orange accent
            spaceAfter=12
        )
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9,
            leading=13,
            textColor=colors.HexColor('#334155')
        )
        h2_style = ParagraphStyle(
            'ReportH2',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=12,
            leading=16,
            textColor=colors.HexColor('#0f172a'),
            spaceBefore=10,
            spaceAfter=6
        )
        meta_label = ParagraphStyle(
            'MetaLabel',
            fontName='Helvetica-Bold',
            fontSize=8,
            leading=11,
            textColor=colors.HexColor('#64748b')
        )
        meta_val = ParagraphStyle(
            'MetaVal',
            fontName='Helvetica',
            fontSize=8,
            leading=11,
            textColor=colors.HexColor('#0f172a')
        )

        story = []

        # 1. Header Banner
        header_table = Table([
            [
                Paragraph("<b>INFERNOX MISSION CONTROL</b><br/><font size=7 color='#64748b'>AI-BASED SATELLITE THERMAL INTELLIGENCE PLATFORM</font>", body_style),
                Paragraph(f"<b>REPORT ID:</b> {payload.metadata.report_id}<br/><b>DATE:</b> {payload.metadata.generated_at[:10]}", ParagraphStyle('RightMeta', parent=meta_label, alignment=2))
            ]
        ], colWidths=[4.0 * inch, 3.5 * inch])
        header_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6)
        ]))
        story.append(header_table)
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#ea580c'), spaceAfter=12, spaceBefore=4))

        # 2. Title & Headline
        story.append(Paragraph(payload.metadata.title, title_style))
        headline = payload.summary.get("headline", payload.metadata.title)
        story.append(Paragraph(f"OPERATIONAL ASSESSMENT: {headline}", subtitle_style))

        # 3. Overview Table
        summary_items = [
            [Paragraph("<b>METRIC</b>", meta_label), Paragraph("<b>VALUE</b>", meta_label)],
            [Paragraph("Report Type", meta_label), Paragraph(payload.metadata.report_type, meta_val)],
            [Paragraph("Generated By", meta_label), Paragraph(payload.metadata.generated_by, meta_val)],
            [Paragraph("Operational Status", meta_label), Paragraph(str(payload.summary.get("operational_status", "ACTIVE")), meta_val)],
            [Paragraph("Severity Tier", meta_label), Paragraph(str(payload.summary.get("severity", "EVALUATED")), meta_val)]
        ]
        sum_table = Table(summary_items, colWidths=[2.5 * inch, 5.0 * inch])
        sum_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        story.append(sum_table)
        story.append(Spacer(1, 10))

        # 4. Detailed Sections
        for sec_name, sec_data in payload.sections.items():
            nice_title = sec_name.replace("_", " ").upper()
            story.append(Paragraph(nice_title, h2_style))

            if isinstance(sec_data, dict):
                rows = [[Paragraph("<b>ATTRIBUTE</b>", meta_label), Paragraph("<b>OBSERVATION / VALUE</b>", meta_label)]]
                for k, v in sec_data.items():
                    if isinstance(v, (dict, list)):
                        v_str = json.dumps(v)[:120] + "..." if len(json.dumps(v)) > 120 else json.dumps(v)
                    else:
                        v_str = str(v)
                    rows.append([
                        Paragraph(k.replace("_", " ").title(), meta_label),
                        Paragraph(v_str, meta_val)
                    ])
                sec_table = Table(rows, colWidths=[2.5 * inch, 5.0 * inch])
                sec_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
                    ('TOPPADDING', (0, 0), (-1, -1), 3),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
                ]))
                story.append(sec_table)
                story.append(Spacer(1, 8))

            elif isinstance(sec_data, list):
                if sec_data and isinstance(sec_data[0], dict):
                    headers = list(sec_data[0].keys())[:5]
                    hdr_row = [Paragraph(f"<b>{h.replace('_', ' ').upper()}</b>", meta_label) for h in headers]
                    table_rows = [hdr_row]
                    for item in sec_data[:10]:
                        row = [Paragraph(str(item.get(h, "")), meta_val) for h in headers]
                        table_rows.append(row)
                    list_table = Table(table_rows, colWidths=[7.5 / len(headers) * inch] * len(headers))
                    list_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f8fafc')),
                        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
                        ('TOPPADDING', (0, 0), (-1, -1), 3),
                        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
                    ]))
                    story.append(list_table)
                elif sec_data:
                    for text_item in sec_data:
                        story.append(Paragraph(f"• {text_item}", body_style))
                story.append(Spacer(1, 8))

        # 5. Data Provenance & Reproducibility Block
        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#cbd5e1'), spaceBefore=10, spaceAfter=8))
        story.append(Paragraph("DATA PROVENANCE & ANALYTICAL REPRODUCIBILITY", h2_style))

        prov_rows = [
            [Paragraph("<b>System / Source</b>", meta_label), Paragraph("<b>Version / Specification</b>", meta_label)],
            [Paragraph("Classification Model", meta_label), Paragraph(payload.provenance.model_version, meta_val)],
            [Paragraph("Feature Schema", meta_label), Paragraph(payload.provenance.feature_schema_version, meta_val)],
            [Paragraph("Risk Engine", meta_label), Paragraph(payload.provenance.risk_model_version, meta_val)],
            [Paragraph("Analytics Service", meta_label), Paragraph(payload.provenance.analytics_version, meta_val)],
            [Paragraph("Upstream Providers", meta_label), Paragraph(", ".join(payload.provenance.data_sources), meta_val)]
        ]
        prov_table = Table(prov_rows, colWidths=[2.5 * inch, 5.0 * inch])
        prov_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]))
        story.append(prov_table)
        story.append(Spacer(1, 6))

        # Disclaimer footer
        disclaimer = "NOTICE: This analytical document is generated automatically by the InfernoX Geospatial Intelligence platform for triage, investigation, and situational awareness. It does not constitute official regulatory emergency dispatch."
        story.append(Paragraph(f"<font size=7 color='#64748b'>{disclaimer}</font>", body_style))

        doc.build(story)
        return buffer.getvalue()

    @staticmethod
    def export_csv(payload: ReportDataPayload) -> str:
        """
        Generate CSV representation of report sections.
        """
        output = io.StringIO()
        writer = csv.writer(output)

        writer.writerow(["Report ID", payload.metadata.report_id])
        writer.writerow(["Report Type", payload.metadata.report_type])
        writer.writerow(["Title", payload.metadata.title])
        writer.writerow(["Generated At", payload.metadata.generated_at])
        writer.writerow(["Model Version", payload.provenance.model_version])
        writer.writerow([])

        # Summary
        writer.writerow(["--- SUMMARY ---"])
        for k, v in payload.summary.items():
            writer.writerow([k, v])
        writer.writerow([])

        # Sections
        for sec_name, sec_data in payload.sections.items():
            writer.writerow([f"--- SECTION: {sec_name.upper()} ---"])
            if isinstance(sec_data, dict):
                for k, v in sec_data.items():
                    writer.writerow([k, json.dumps(v) if isinstance(v, (dict, list)) else v])
            elif isinstance(sec_data, list):
                if sec_data and isinstance(sec_data[0], dict):
                    headers = list(sec_data[0].keys())
                    writer.writerow(headers)
                    for item in sec_data:
                        writer.writerow([item.get(h, "") for h in headers])
                else:
                    for item in sec_data:
                        writer.writerow([item])
            writer.writerow([])

        return output.getvalue()

    @staticmethod
    def export_geojson(payload: ReportDataPayload) -> Dict[str, Any]:
        """
        Generate GeoJSON FeatureCollection for spatial data in the report.
        """
        features = []
        sections = payload.sections

        # Check thermal evidence coordinates
        if "thermal_evidence" in sections:
            t_ev = sections["thermal_evidence"]
            lat = t_ev.get("latitude")
            lon = t_ev.get("longitude")
            if lat is not None and lon is not None:
                features.append({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [float(lon), float(lat)]
                    },
                    "properties": {
                        "entity_type": "THERMAL_EVENT",
                        "event_id": t_ev.get("event_id"),
                        "frp_mw": t_ev.get("frp_mw"),
                        "detected_at": t_ev.get("detected_at"),
                        "report_id": payload.metadata.report_id
                    }
                })

        # Check facility profile coordinates
        if "facility_profile" in sections:
            fac = sections["facility_profile"]
            lat = fac.get("latitude")
            lon = fac.get("longitude")
            if lat is not None and lon is not None:
                features.append({
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [float(lon), float(lat)]
                    },
                    "properties": {
                        "entity_type": "INDUSTRIAL_FACILITY",
                        "name": fac.get("name"),
                        "facility_type": fac.get("type"),
                        "osm_id": fac.get("osm_id")
                    }
                })

        # Fallback dummy center if empty
        if not features:
            features.append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [78.9629, 20.5937]
                },
                "properties": {
                    "report_id": payload.metadata.report_id,
                    "title": payload.metadata.title
                }
            })

        return {
            "type": "FeatureCollection",
            "report_metadata": payload.metadata.model_dump(),
            "features": features
        }

    @staticmethod
    def export_json(payload: ReportDataPayload) -> str:
        """
        Generate formatted JSON representation of the report.
        """
        return payload.model_dump_json(indent=2)
